version: '3.8'

services:
  client:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app 
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
    networks:
          - my_network 
networks:
      my_network:
        external: true  