
services:
  auth:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./auth:/usr/src/app 
    ports:
      - "5000:5000" 
    command: npm start
    environment:
      - NODE_ENV=development 
    networks:
      - tcg_network  # Updated to use the new network name

networks:
  tcg_network:  # Updated to use the new network name
    external: true