version: '3.8'

services:
  auth:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./auth:/usr/src/app 
    ports:
      - "5000:5000" 
    command: npm start
    environment:
      - NODE_ENV=development 
    networks:
      - my_network  
networks:
      my_network:
        external: true 