
networks:
  tcg_network:
    external: true  # Asegúrate de que esta red exista
x-env_mongo_credentials: &env_mongo_credentials
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}  # Usuario root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example_password} # Contraseña del usuario root
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_users
    ports:
      - "27017:27017"  # Exponer el puerto de MongoDB
    volumes:
      - ./mongodb_data/mongo_users:/data/db  # Montar el volumen para persistir datos en la ruta correcta
      - ./init/auth:/docker-entrypoint-initdb.d  # Script de inicialización
    networks:
      - tcg_network  # Conectar a la red tcg_network
    environment:

      <<:
        - *env_mongo_credentials



      MONGO_INITDB_DATABASE: mongo_users  # Base de datos inicial


volumes:
  mongodb_data:  # Definición del volumen para MongoDB